### ISSUE TITLE
Previously working code fails with "Bind variable ? not set" folowing upgrade from 1.6.13 

### ISSUE THREAD

**Issue by markddrake** [snowflakedb/snowflake-connector-nodejs#369]
Please answer these questions before submitting your issue. Thanks!
```
C:\Development\bind>node --version
v18.9.0

C:\Development\bind>npm --version
7.21.0

C:\Development\bind>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
Running the following program 

```
C:\Development\bind>type test.js
import snowflake from 'snowflake-sdk';

import fs                 from "fs"

import {
  performance
}                         from 'perf_hooks';


class Tester {

   constructor() {

          this.connectionProperties =  {
            "account"                       : "*****************"
      , "username"                      : "*****************"
      , "password"                      : "*****************"
          , "warehouse"                     : "DEMO_WH"
      , "database"                      : "DEMO_DB"
          , "schema"                        : "PUBLIC"
    }
  }

  establishConnection(connection) {

    return new Promise((resolve,reject) => {
      connection.connect((err,connection) => {
        if (err) {
          reject(err)
        }
        resolve(connection)
      })
    })
  }

  executeSQL(sqlStatement,binds) {

    return new Promise((resolve,reject) => {

          this.connection.execute({
        sqlText        : sqlStatement
      , binds          : binds
          , fetchAsString  : ['Number','Date','JSON']
      , complete       : async (err,statement,rows) => {
                           if (err) reject(err)
                           resolve(rows)
                             }
      })
    })
  }

  async runTest() {

     const fileContent = JSON.parse(fs.readFileSync('dataset.json','utf-8'));
         const ROWS = fileContent.length
         const dataset = fileContent.flat().map((x) => { return typeof x === 'object' ? JSON.stringify(x) : x})

     const placeHolder = '(?,?,?,?,?)';
         const sqlText = `insert into "YTEST"."audit" ("id","type","data","createdDateTime","action") select COLUMN1,COLUMN2,TRY_PARSE_JSON(COLUMN3),COLUMN4,COLUMN5 from values ${new Array(ROWS).fill(0).map(() => {return placeHolder}).join(',')}`

     let count = 0
         for (let next of sqlText) {
           count+= next === '?'  ? 1 : 0
         }

         try {
       this.connection = snowflake.createConnection(this.connectionProperties)
       this.connection = await this.establishConnection(this.connection)
       await this.executeSQL('DROP SCHEMA IF EXISTS YTEST');
       await this.executeSQL('CREATE SCHEMA YTEST');
       await this.executeSQL('create table "YTEST"."audit"( "id" INT ,"type" VARCHAR(40) ,"data" VARIANT ,"createdDateTime" TIMESTAMP_TZ(0) ,"action" VARCHAR(256) );');

           await this.executeSQL(sqlText,dataset);
         } catch (e) {
           console.log(e);
         }
   }
}

async function main() {
  const t = new Tester()
  await t.runTest()
}

main().then(() => {console.log('Success')}).catch((e) => {console.log(e)})


```
works with 1.6.13
```
C:\Development\bind>npm install snowflake-sdk@1.6.13

changed 1 package, and audited 264 packages in 864ms

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Development\bind>npm list
bind@ C:\Development\bind
`-- snowflake-sdk@1.6.13

C:\Development\bind>node test.js
Success
```
But fails after upgrading to 1.6.14 or later
```
C:\Development\bind>npm install snowflake-sdk@1.6.14

changed 1 package, and audited 264 packages in 873ms

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Development\bind>npm list
bind@ C:\Development\bind
`-- snowflake-sdk@1.6.14


C:\Development\bind>node test.js
Error [OperationFailedError]: SQL compilation error: error line 1 at position 152
Bind variable ? not set.
    at createError (C:\Development\bind\node_modules\snowflake-sdk\lib\errors.js:536:15)
    at exports.createOperationFailedError (C:\Development\bind\node_modules\snowflake-sdk\lib\errors.js:315:10)
    at Object.callback (C:\Development\bind\node_modules\snowflake-sdk\lib\services\sf.js:647:28)
    at C:\Development\bind\node_modules\snowflake-sdk\lib\http\base.js:111:25
    at done (C:\Development\bind\node_modules\urllib\lib\urllib.js:589:5)
    at C:\Development\bind\node_modules\urllib\lib\urllib.js:953:9
    at decodeContent (C:\Development\bind\node_modules\urllib\lib\urllib.js:740:14)
    at handleResponseCloseAndEnd (C:\Development\bind\node_modules\urllib\lib\urllib.js:924:7)
    at IncomingMessage.<anonymous> (C:\Development\bind\node_modules\urllib\lib\urllib.js:962:7)
    at IncomingMessage.emit (node:events:525:35) {
  code: '002049',
  sqlState: '42601',
  data: {
    internalError: false,
    errorCode: '002049',
    age: 0,
    sqlState: '42601',
    queryId: '01a8af6b-0402-4037-000d-5483012d3f66',
    line: -1,
    pos: -1,
    type: 'COMPILATION'
  }
}
Success

C:\Development\bind>npm install snowflake-sdk@1.6.16

changed 1 package, and audited 264 packages in 1s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Development\bind>npm list
bind@ C:\Development\bind
`-- snowflake-sdk@1.6.16


C:\Development\bind>node test.js
Error [OperationFailedError]: SQL compilation error: error line 1 at position 152
Bind variable ? not set.
    at createError (C:\Development\bind\node_modules\snowflake-sdk\lib\errors.js:537:15)
    at exports.createOperationFailedError (C:\Development\bind\node_modules\snowflake-sdk\lib\errors.js:316:10)
    at Object.callback (C:\Development\bind\node_modules\snowflake-sdk\lib\services\sf.js:647:28)
    at C:\Development\bind\node_modules\snowflake-sdk\lib\http\base.js:111:25
    at done (C:\Development\bind\node_modules\urllib\lib\urllib.js:589:5)
    at C:\Development\bind\node_modules\urllib\lib\urllib.js:953:9
    at decodeContent (C:\Development\bind\node_modules\urllib\lib\urllib.js:740:14)
    at handleResponseCloseAndEnd (C:\Development\bind\node_modules\urllib\lib\urllib.js:924:7)
    at IncomingMessage.<anonymous> (C:\Development\bind\node_modules\urllib\lib\urllib.js:962:7)
    at IncomingMessage.emit (node:events:525:35) {
  code: '002049',
  sqlState: '42601',
  data: {
    internalError: false,
    errorCode: '002049',
    age: 0,
    sqlState: '42601',
    queryId: '01a8af6b-0402-4037-000d-5483012d3fc6',
    line: -1,
    pos: -1,
    type: 'COMPILATION'
  }
}
Success

**Comment by markddrake** [comment]
[dataset.zip](https://github.com/snowflakedb/snowflake-connector-nodejs/files/10136410/dataset.zip)

**Comment by sfc-gh-dszmolka** [comment]
#358  ?

**Comment by sfc-gh-dszmolka** [comment]
while debugging this issue with one of our customers, we found that setting `connection` option `arrayBindingThreshold` to a higher value can help circumvent this issue. This parameter is available from version `1.6.17` and up, and has a default value of `100000`.  example usage (for JS):
```
var connection = snowflake.createConnection({
  account: process.env.SFACCOUNT,
  username: process.env.SFUSER,
..
  arrayBindingThreshold: 1000000 //default = 100000
});
```


Its exact new value depends on the amount of data-to-be-inserted, and can be confirmed with setting `snowflake.configure({ logLevel: 'trace' });` and looking for a logline having `numBinds` after reproducing the issue.

setting `arrayBindingThreshold` above the value of `numBinds` should help avoid the issue until the proper fix is out, which is still in the making at this moment of writing.
alternatively you can bump `arrayBindingThreshold` (e.g. to 1 million or higher) and see if it works in your case, but for more 'precise' measurements the above method can be used.
yet another alternative, as already discovered, to just keep the driver at version `1.6.13` or below.

hope this helps you folks to mitigate the issue until we are able to properly fix the driver. thank you for bearing with us !

**Comment by sfc-gh-dszmolka** [comment]
#439

**Comment by sfc-gh-dszmolka** [comment]
release `snowflake-sdk@1.6.20` is out with the fix PR. please upgrade to the fixed version and re-test.
if the issue still persists, please reopen the issue or comment with the details and I'll reopen it.
